FROM docker.io/opencontrailnightly/{{ image_name }}:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

ENV BUILD_SYSTEM=kolla

{% block contrail_external_zookeeper_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block contrail_external_zookeeper_footer %}{% endblock %}
{% block footer %}{% endblock %}
